#!/bin/sh
# lint, if linting errors, then format, then lint again
make lint
if [ $? -ne 0 ]; then
    echo "lint errors. attempting to format."
    make format
    if [ $? -ne 0 ]; then
        echo "format found errors. Aborting commit."
        exit 1
    fi
    make lint
    if [ $? -ne 0 ]; then
        echo "lint errors. Aborting commit."
        exit 1
    fi
fi

# ensure package and project versions match
pytest -k test_version
if [ $? -ne 0 ]; then
    echo "version mismatch. Aborting commit."
    exit 1
fi

# ensure memory size tests pass
pytest -k test_memory_size
if [ $? -ne 0 ]; then
    echo "memory size test errors. Aborting commit."
    exit 1
fi

# If there are no errors, continue with the commit
exit 0